auth/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView, LoginView

app_name = 'auth'

urlpatterns = [
    path('register/', views.UserFormView.as_view(), name='register'),

    path('login/', LoginView.as_view(), name='login'),

    path('logout/', LogoutView.as_view(), name='logout'),

]

music/urls.py
from django.urls import path
from . import views


app_name = 'music'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    path('<int:pk>/song-add/', views.SongCreate.as_view(), name='song-add'),

    path('all-songs/', views.AllSong.as_view(), name='all-songs'),

    path('<int:pk>/song-delete/', views.SongDelete.as_view(), name='song-delete'),

    path('<int:pk>/song-toggle-favorite/', views.favorite, name='song-toggle-favorite'),

    path('<int:pk>/album-toggle-favorite/', views.favorite_album, name='album-toggle-favorite'),

    path('<int:pk>/', views.DetailView.as_view(), name="detail"),

    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),

    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),

    path('album/<int:pk>/delete/', views.AlbumDelete.as_view(), name='album-delete'),


]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls', namespace='auth')),
    path('', include('music.urls', namespace='music')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Album(models.Model):
    user = models.ForeignKey(User, default=1, on_delete=models.DO_NOTHING)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + " - " + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    song_file = models.FileField(upload_to='musics/')
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:song-add', kwargs={'pk': self.pk})

    def __str__(self):
        return self.song_title

music/forms.py
from django import forms
from .models import Song


class SongFrom(forms.ModelForm):
    # is_favorite = forms.RadioSelect()

    class Meta:
        model = Song
        fields = ['file_type', 'song_title', 'song_file', 'is_favorite']

music/views.py
from django.http import JsonResponse
from django.views import generic
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import SongFrom
from .models import Album, Song
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    template_name = 'music/detail.html'
    model = Album


class AlbumCreate(LoginRequiredMixin, CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

    # def get(self, request, *args, **kwargs):
    #     self.user = request.user
    #     return super(AlbumCreate, self).get(self, request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        print(form.instance.user)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('music:index')


class AlbumUpdate(LoginRequiredMixin, UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumDelete(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')


class SongCreate(LoginRequiredMixin, CreateView):
    form_class = SongFrom
    model = Song

    def get_success_url(self):
        return reverse_lazy('music:song-add', kwargs={'pk': self.object.album.pk})

    def form_valid(self, form):
        album = get_object_or_404(Album, pk=self.kwargs['pk'])
        form.instance.album = album
        return super(SongCreate, self).form_valid(form)


class SongDelete(LoginRequiredMixin, DeleteView):
    model = Song

    def get_success_url(self, **kwargs):

        return reverse_lazy('music:detail', kwargs={'pk': self.object.album.pk})

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(pk=self.kwargs['pk'])


def favorite(request, pk):
    song = get_object_or_404(Song, pk=pk)
    try:
        if song.is_favorite:
            song.is_favorite = False
        else:
            song.is_favorite = True
        song.save()
    except (KeyError, Song.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return redirect('music:detail', pk=song.album.id)


def favorite_album(request, pk):
    album = get_object_or_404(Album, pk=pk)
    try:
        if album.is_favorite:
            album.is_favorite = False
        else:
            album.is_favorite = True
        album.save()
    except (KeyError, Album.DoesNotExist):
        return JsonResponse({'success': False})
    else:
        return redirect('music:index')


class AllSong(ListView):
    model = Song
    template_name = 'music/all_song.html'

#
# def songToggleFavorite(request, pk):
#     print(pk)
#     song = get_object_or_404(Song, pk=pk)
#     # song = song.save(commit=False)
#     per_fev = song.is_favorite
#     # print(per_fev)
#     # song = song.save(commit=False)
#     song.is_favorite = not per_fev
#     song.save()
#     print(song.album.id)
#     return reverse_lazy('music:detail', kwargs={'pk': song.album.id})
#
#
# class SongToggleFavorite(LoginRequiredMixin, UpdateView):
#     model = Song
#     # template_name = 'music/detail.html'
#
#     fields = ('is_favorite', )
#
#     def form_valid(self, form):
#         song = form.save(commit=False)
#         pre_fev = self.object.is_favorite
#         # print(pre_fev)
#         song.is_favorite = pre_fev
#         song.save()
#         return super(SongToggleFavorite, self).form_valid(form)
#
#     def get_success_url(self, **kwargs):
#
#         return reverse_lazy('music:detail', kwargs={'pk': self.object.album.pk})
#
#     def get_queryset(self):
#         qs = super().get_queryset()
#         return qs.filter(pk=self.kwargs['pk'])

templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %} Add a new album{% endblock %}


{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="Submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/music/all_song.html
{% extends 'music/base.html' %}
{% block title %}Album detail{% endblock %}
{% block content %}

    <div class="container-fluid songs-container">

        <div class="row">


            <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Songs</h3>
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Uploaded By</th>
                            </tr>
                            </thead>
                            <tbody>

                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>

                                    <td>{{ song.album.artist }}</td>
                                    <td >
                                        <audio src="{{ song.song_file.url }}" preload="auto"></audio>
                                    </td>
                                    <td>{{ song.album.user}}</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

templates/music/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}folk{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'music/css/bootstrap.min.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link rel="icon" href="{% static 'music/images/disk.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'music/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'music:index' %}">Flock</a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd"
                                                                         aria-hidden="true"></span>&nbsp; Albums</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'music:all-songs' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                    Songs</a>
            </li>

        </ul>
        <form class="navbar-form navbar-right" role="search" method="get" action="{% url 'music:index' %}">
            <div class="form-group">
                <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
        </form>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0 navbar-right">



            {% if request.user.is_authenticated %}


                  <li class="nav-item">
                <a class="nav-link" href="{% url 'music:album-add' %}"><span class="glyphicon glyphicon-plus"
                                                                             aria-hidden="true"></span>&nbsp;Add
                    Album</a>
            </li>

                <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                    Logout</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="#"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;
                    {{request.user.username}}</a>
            </li>

                {% else %}


                <li class="nav-item">
                <a class="nav-link" href="{% url 'auth:login' %}"><span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp;
                    Login</a>
            </li>

            {% endif %}


        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
<script src="{% static 'music/js/bootstrap.min.js' %}"></script>
<script src="{% static 'music/audiojs/audiojs/audio.min.js' %}"></script>
<script>
  audiojs.events.ready(function() {
    var as = audiojs.createAll();
  });
</script>
</body>
</html>

templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album detail{% endblock %}
{% block content %}

    <div class="container-fluid songs-container">

        <div class="row">

            <!-- Left Album Info -->
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <a href="#">
                            {% if album.album_logo %}
                                <img src="{{ album.album_logo.url }}" class="img-responsive">
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        </a>
                        <h1>{{ album.album_title }}
                            <small>{{ album.genre }}</small>
                        </h1>
                        <h2>{{ album.artist }}</h2>
                    </div>
                </div>
            </div>

            <!-- Right Song Info -->
            <div class="col-sm-8 col-md-9">

                <ul class="nav nav-pills" style="margin-bottom: 10px;">
                    <li role="presentation" class="active"><a href="#">View All</a></li>

                    <li role="presentation" ><a class="btn btn-outline-primary" href="{% url 'music:song-add' object.pk %}">Add New Song</a></li>
                </ul>

                <div class="panel panel-default">
                    <div class="panel-body">

                        <h3>All Songs</h3>

                        {% if error_message %}
                            <p><strong>{{ error_message }}</strong></p>
                        {% endif %}

                        <table class="table">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th>Audio File</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for song in album.song_set.all %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td >
                                        <audio src="{{ song.song_file.url }}" preload="auto" />
{#                                        <a target="controls" href="{{ song.song_file.url }}">#}
{#                                            <button type="button" class="btn btn-success btn-xs">#}
{#                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play#}
{#                                            </button>#}
{#                                        </a>#}
{#                                        <audio controls>#}
{#                                                <source src="{{ song.audio_file.url }}" type="audio/mpeg">#}
{#                                    </audio>#}
                                    </td>
                                    <td>
                                        <a href="{% url 'music:song-toggle-favorite' song.id %}" class="btn-favorite"><span
                                                class="glyphicon  {% if song.is_favorite %}glyphicon-star {% else %} glyphicon-star-empty{% endif %}"></span></a>
                                    </td>
                                    <td>
                                        <form action="{% url 'music:song-delete' song.id %}" method="post"
                                              style="display: inline;">
                                            {% csrf_token %}
                                            <input type="hidden" name="song_id" value="{{ song.id }}"/>
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>

        </div>

    </div>
{% endblock %}

templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
    <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/music/index.html
{% extends 'music/base.html' %}
{% block content %}

    <div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img style="height: 30rem; width: 50rem;object-fit: cover;"  src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>
                            <h4>Created by: {{ album.user }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %} " class="btn btn-primary btn-sm" role="button">View
                                Details</a>

                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post"
                                  style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="{% url 'music:album-toggle-favorite' album.id %}"
                               class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon {% if album.is_favorite %}glyphicon-star {% else %} glyphicon-star-empty{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
    </div>


{% endblock %}

templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %} registration {% endblock %}
{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Create a new account</h3>
                    <form action="" class="form-horizontal" method="post" enctype="multipart/form-data">
                        {% include 'music/form-template.html' %}
                         {% csrf_token %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success" type="Submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}